### ISSUE TITLE
Use hashes for function table entries and not just a random number.

### ISSUE THREAD

**Issue by fabulousduck** [fabulousduck/smol#31]
Currently, to make ID's for function on the function table, we use a random number between 0 and 1000. This is very bad as it is collision prone. This should ideally be done in a way that uses hashes. the line of code that is the culprit can be found [here](https://github.com/fabulousduck/smol/blob/e92ef5e83429c80de80a7ceeefe619dfac923826/ir/ir.go#L122).

**Comment by u5surf** [comment]
@fabulousduck 
Can we change the type of ID?
https://github.com/fabulousduck/smol/blob/e92ef5e83429c80de80a7ceeefe619dfac923826/ir/jmp.go#L10-L11
How about using `hash/func` which calculates lightly?
https://golang.org/pkg/hash/fnv/#New64a

**Comment by ghostsquad** [comment]
Or a guid

**Comment by fabulousduck** [comment]
Hey, @u5surf. Using the `hash/func` functions for this is fine. And of course if you need to change the type of the ID you are more than welcome to. Please do check that where this ID is used, you also change the types accordingly.

**Comment by u5surf** [comment]
@ghostsquad 
UUID is a great suggestion you have. At first, I was also trying `github.com/google/uuid,` but It could generate a random value only in supposing error free(see the following docs).
https://godoc.org/github.com/google/uuid#NewRandom

@fabulousduck 
If it can be ignoring the uuid generating error, I’d like to adopt the his proposals. 
WDYT?

**Comment by ghostsquad** [comment]
I would suggest not ignoring the error, but a panic is probably acceptable way to deal with a potential error from this. Though, I haven't read the code, so I'm unsure of what conditions apply that could cause an error to occur.
